[platformio]
; Временно: .pio/build заблокирован на диске, собираем в другую папку
build_dir = .pio/build_flash

[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Увеличиваем раздел приложения, так как LVGL занимает место
board_build.partitions = min_spiffs.csv

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    bodmer/TFT_eSPI @ ^2.5.43       ; Драйвер дисплея
    lvgl/lvgl @ ^8.3.11             ; Графическая библиотека
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git ; Драйвер тачскрина

build_flags =
    ; --- Настройки для платы CYD (ESP32-2432S028) ---
    -D USER_SETUP_LOADED=1
    
    ; Драйвер дисплея (обычно ILI9341 для этой платы)
    -D ILI9341_2_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    
    ; Настройки SPI
    -D SPI_FREQUENCY=55000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    
    ; Настройки тачскрина
    ; -D TOUCH_CS=33 ; Отключаем, так как используем отдельную библиотеку и SPI шину
    
    ; Настройки LVGL
    -D LV_CONF_SKIP
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_TICK_CUSTOM=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_22=1
    -D LV_FONT_MONTSERRAT_18=1
    -D LV_FONT_MONTSERRAT_16=1